name: maxitivity
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  animations: ^2.0.8
  awesome_notifications: ^0.8.2
  awesome_notifications_core: ^0.8.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_ringtone_player: ^3.2.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  logger: ^1.4.0
  percent_indicator: ^4.2.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

